### PR TITLE
Fixed 'extend' functionality

### PR DESCRIPTION
**Pull request by NyroTheCat**
added missing array key

### CODE REVIEW

**Comment by ChadSikorra** [comment]
Nice catch. I should be able to merge this later tonight and add a spec.

**Comment by ChadSikorra** [comment]
Checking this out at lunch. But I'm not so sure this fixes the issue. I think it still expects that the `type` is defined, such as:

```
objects:
    foo:
        extends: [ foo, bar ]
        type: specialUser
```

Or what use case are you basing this off at the moment? I think what I need to do is merge any extended schemas before attempting to get the schema type from the array.

So I think this order is the current issue:

```
    protected function parseYamlForObject(array $schema, $schemaName, $objectType)
    {
        $objectSchema = $this->getObjectFromSchema($schema, $objectType);
        $objectSchema = $this->mergeAnyExtendedSchemas($objectSchema, $schemaName);
```

**Comment by NyroTheCat** [comment]
i ran into a problem extending a schema type (not a file). it permanently gave me this error: `Cannot find object type "" in schema.`

i'm using a similar schema definition as shown in your example. while the schema file `foo.yaml` is found, the second array value `bar` is not recognized and therefore _blank_. this gives me the exception. i tracked the problem down to this line i have changed. now the second array key is returned properly.

**Comment by ChadSikorra** [comment]
Ah, ok.  I think I understand what you mean now. I think I found a separate issue too while I was trying to figure it out. Thought of a few other improvements I should probably make while I'm at it.

**Comment by ChadSikorra** [comment]
Merged, thanks! I added a spec for it too: https://github.com/ldaptools/ldaptools/commit/c977ab2e2423bc70ecec9d853502ad7d85927556

**Pull request merged**
